components:
  bssmw:
    name: 'BSSMW'
    base_url: 'https://gorest.co.in'
    version:
      - name: 'V1'
        base_url: 'https://gorest.co.in'
        apis:
          - name: "first_test_api"
            url: "public/v2/posts"
            base_url: "https://gorest.co.in"
            verb: "GET"
            type: "json"
          - name: "second_test_api"
            base_url: "https://httpbin.org"
            url: "post"
            verb: "POST"
            type: "json"
          - name: "third_test_api"
            base_url: "https://httpbin.org"
            url: "post"
            verb: "POST"
            type: "urlencoded"
          - name: "fourth_test_api"
            base_url: "https://httpbin.org"
            url: "put"
            verb: "PUT"
            type: "json"
  telco:
    name: 'Telco'
    version:
      - name: 'V2'
        base_url: 'https://gorest.co.in'
        apis:
          - name: "first_test_api"
            base_url: "https://httpbin.org"
            url: "put"
            verb: "PUT"
            type: "urlencoded"
          - name: "second_test_api"
            url: "public/v2/users"
            verb: "GET"
            type: "json"